# -*- coding: utf-8 -*-
"""Aygaz_Bootcamp_Bitirme_Projesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gyt6M_XcbXHJBCw17vqN9aNDO4pAtkJl
"""

import random

secenekler = ["taş", "kağıt", "makas"]

# Kuralları programa anlatma şeklimiz :)
def kazanani_bul(kullanici_secimi, bilgisayar_secimi):
    if kullanici_secimi == bilgisayar_secimi:
        return "Berabere!"
    elif (kullanici_secimi == "taş" and bilgisayar_secimi == "makas") or \
         (kullanici_secimi == "kağıt" and bilgisayar_secimi == "taş") or \
         (kullanici_secimi == "makas" and bilgisayar_secimi == "kağıt"):
        return "Kullanici"
    else:
        return "Bilgisayar"

# Oyun fonksiyonumuz
def tas_kagit_makas_ENES_CİCEK():
    print("Taş-Kağıt-Makas oyununa hosgeldiniz!\n-------------------------------------------\nKURALLAR\n-------------------------------------------\n1) Taş Makası yener.\n2) Kağıt Taşı yener.\n3) Makas Kağıdı yener.\n4) Oyun 3 tur oynanır ve 2 tur kazanan galip gelir.")

    kullanici_skoru = 0
    bilgisayar_skoru = 0
    gereken_kazanma_sayisi = 2

    while kullanici_skoru < gereken_kazanma_sayisi and bilgisayar_skoru < gereken_kazanma_sayisi:
        kullanici_secimi = input("taş, kağıt, makas? (Cikmak icin 'q' tusuna basin): ").lower() # Olası büyük küçük harf yazımlarından hata almamak için.

        if kullanici_secimi == 'q':
            print("Oyun bitti.")
            break
        elif kullanici_secimi not in secenekler:
            print("Gecersiz secim, lutfen tekrar deneyin.")
            continue

        bilgisayar_secimi = random.choice(secenekler)
        print(f"Bilgisayarin secimi: {bilgisayar_secimi}")

        kazanan = kazanani_bul(kullanici_secimi, bilgisayar_secimi)

        if kazanan == "Kullanici":
            kullanici_skoru += 1
            print("Tebrikler, bu turu kazandiniz!")
        elif kazanan == "Bilgisayar":
            bilgisayar_skoru += 1
            print("Bilgisayar bu turu kazandi.")
        else:
            print("Bu tur berabere!")

        print(f"Skor: Kullanici {kullanici_skoru} - {bilgisayar_skoru} Bilgisayar")

    if kullanici_skoru > bilgisayar_skoru:
        print("Tebrikler! Taş-Kağıt-Makas oyununu kazandiniz!")
    else:
        print("Bilgisayar Taş-Kağıt-Makas oyununu kazandi.")

# Oyunu başlat
tas_kagit_makas_ENES_CİCEK()